### ISSUE TITLE
nginx[27376]: segfault at 7f12e2a71ff3 ip 0000000000519331 sp 00007fffaf4b0070 error 7 in nginx[400000+396000]

### ISSUE THREAD

**Issue by sdcuike** [openresty/lua-nginx-module#1337]
core content is：

#0  0x0000000000519331 in ngx_http_lua_ffi_shdict_incr (zone=0x13da190, key=0x41f6e150 "10.10.132.46", key_len=12, value=0x41a28900, err=0x41a28980, has_init=1, init=1, init_ttl=1101171008, 
    forcible=0x7f12e2a71ff3) at /data/soft/lua-nginx-module/src/ngx_http_lua_shdict.c:2649
2649        *forcible = 0;

why？

---
dmesg concrete details：

[xxxxxx]$ dmesg |grep  27376
nginx[27376]: segfault at 7f12e2a71ff3 ip 0000000000519331 sp 00007fffaf4b0070 error 7 in nginx[400000+396000]
 
-----

core details

[xxxxxxxxx data]$ gdb /data/server/nginx/sbin/nginx core.27376
GNU gdb (GDB) Red Hat Enterprise Linux (7.2-92.el6)
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /data/server/nginx/sbin/nginx...done.
[New Thread 27376]
Reading symbols from /lib64/libpthread.so.0...(no debugging symbols found)...done.
[Thread debugging using libthread_db enabled]
Loaded symbols for /lib64/libpthread.so.0
Reading symbols from /lib64/libdl.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/libdl.so.2
Reading symbols from /lib64/libcrypt.so.1...(no debugging symbols found)...done.
Loaded symbols for /lib64/libcrypt.so.1
Reading symbols from /usr/local/luajit/lib/libluajit-5.1.so.2...(no debugging symbols found)...done.
Loaded symbols for /usr/local/luajit/lib/libluajit-5.1.so.2
Reading symbols from /lib64/libm.so.6...(no debugging symbols found)...done.
Loaded symbols for /lib64/libm.so.6
Reading symbols from /lib64/libpcre.so.0...(no debugging symbols found)...done.
Loaded symbols for /lib64/libpcre.so.0
Reading symbols from /lib64/libz.so.1...(no debugging symbols found)...done.
Loaded symbols for /lib64/libz.so.1
Reading symbols from /lib64/libc.so.6...(no debugging symbols found)...done.
Loaded symbols for /lib64/libc.so.6
Reading symbols from /lib64/ld-linux-x86-64.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/ld-linux-x86-64.so.2
Reading symbols from /lib64/libfreebl3.so...(no debugging symbols found)...done.
Loaded symbols for /lib64/libfreebl3.so
Reading symbols from /lib64/libgcc_s.so.1...(no debugging symbols found)...done.
Loaded symbols for /lib64/libgcc_s.so.1
Reading symbols from /lib64/libnss_files.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/libnss_files.so.2
Reading symbols from /usr/local/lib/lua/5.1/cjson.so...(no debugging symbols found)...done.
Loaded symbols for /usr/local/lib/lua/5.1/cjson.so
Core was generated by `nginx: worker process        '.
Program terminated with signal 11, Segmentation fault.
#0  0x0000000000519331 in ngx_http_lua_ffi_shdict_incr (zone=0x13da190, key=0x41f6e150 "10.10.132.46", key_len=12, value=0x41a28900, err=0x41a28980, has_init=1, init=1, init_ttl=1101171008, 
    forcible=0x7f12e2a71ff3) at /data/soft/lua-nginx-module/src/ngx_http_lua_shdict.c:2649
2649        *forcible = 0;
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.209.el6_9.2.x86_64 libgcc-4.4.7-18.el6_9.2.x86_64 nss-softokn-freebl-3.14.3-23.3.el6_8.x86_64 pcre-7.8-7.el6.x86_64 zlib-1.2.3-29.el6.x86_64
(gdb) bf
Undefined command: "bf".  Try "help".
(gdb) bt
#0  0x0000000000519331 in ngx_http_lua_ffi_shdict_incr (zone=0x13da190, key=0x41f6e150 "10.10.132.46", key_len=12, value=0x41a28900, err=0x41a28980, has_init=1, init=1, init_ttl=1101171008, 
    forcible=0x7f12e2a71ff3) at /data/soft/lua-nginx-module/src/ngx_http_lua_shdict.c:2649
#1  0x00007f130cb5fce2 in ?? ()
#2  0x0000000041a28940 in ?? ()
#3  0x00007f12e2a71ff3 in ?? () from /usr/local/luajit/lib/libluajit-5.1.so.2
#4  0x0000000000512d46 in ngx_http_lua_run_thread (L=0x41f53378, r=0x133d300, ctx=0x1541720, nrets=0) at /data/soft/lua-nginx-module/src/ngx_http_lua_util.c:1010
#5  0x00000000005165b0 in ngx_http_lua_access_by_chunk (L=0x41f53378, r=0x133d300) at /data/soft/lua-nginx-module/src/ngx_http_lua_accessby.c:336
#6  0x000000000051677d in ngx_http_lua_access_handler_file (r=0x133d300) at /data/soft/lua-nginx-module/src/ngx_http_lua_accessby.c:232
#7  0x0000000000516b30 in ngx_http_lua_access_handler (r=0x133d300) at /data/soft/lua-nginx-module/src/ngx_http_lua_accessby.c:163
#8  0x0000000000485b16 in ngx_http_core_access_phase (r=0x133d300, ph=0x15beea0) at src/http/ngx_http_core_module.c:1218
#9  0x0000000000480b03 in ngx_http_core_run_phases (r=0x133d300) at src/http/ngx_http_core_module.c:934
#10 0x0000000000480c21 in ngx_http_handler (r=<value optimized out>) at src/http/ngx_http_core_module.c:917
#11 0x000000000048d276 in ngx_http_process_request (r=0x133d300) at src/http/ngx_http_request.c:1930
#12 0x000000000048d8c7 in ngx_http_process_request_headers (rev=<value optimized out>) at src/http/ngx_http_request.c:1360
#13 0x000000000048de8a in ngx_http_process_request_line (rev=0x7f12cb6dc2e8) at src/http/ngx_http_request.c:1031
#14 0x000000000048e498 in ngx_http_wait_request_handler (rev=0x7f12cb6dc2e8) at src/http/ngx_http_request.c:500
#15 0x00000000004695e3 in ngx_event_process_posted (cycle=0x134ceb0, posted=0xa048d0) at src/event/ngx_event_posted.c:33
#16 0x0000000000469362 in ngx_process_events_and_timers (cycle=0x134ceb0) at src/event/ngx_event.c:278
#17 0x0000000000471e88 in ngx_worker_process_cycle (cycle=0x134ceb0, data=<value optimized out>) at src/os/unix/ngx_process_cycle.c:880
#18 0x000000000046e742 in ngx_spawn_process (cycle=0x134ceb0, proc=0x471d86 <ngx_worker_process_cycle>, data=0x2, name=0x6ab074 "worker process", respawn=10) at src/os/unix/ngx_process.c:198
#19 0x000000000047292f in ngx_reap_children (cycle=0x134ceb0) at src/os/unix/ngx_process_cycle.c:659
#20 ngx_master_process_cycle (cycle=0x134ceb0) at src/os/unix/ngx_process_cycle.c:189
#21 0x000000000044fe53 in main (argc=<value optimized out>, argv=<value optimized out>) at src/core/nginx.c:453
(gdb)

**Comment by sdcuike** [comment]
![wechatimg598](https://user-images.githubusercontent.com/2599771/41136983-720cf38c-6b0b-11e8-89fb-78c104ac5964.jpeg)
