### ISSUE TITLE
segmentfault

### ISSUE THREAD

**Issue by mrpre** [openresty/lua-nginx-module#1504]
Nginx: Tengine 2.3.0 (with ngx_lua_module v0.10.14rc4)  

Configure:  
```
http {
    init_by_lua_file ./a.lua;
    lua_shared_dict dogs 10m;
    server {
        listen       8080;
        server_name  localhost;

        location / {
            content_by_lua 'ngx.say("hello")';
            #root   html;
            #index  index.html index.htm;
        }

    }   
}
```  
Run:
./nginx -t  

Stack:  
```
(gdb) bt
#0  0x00007ffff752286d in lua_pushfstring () from /lib64/libluajit-5.1.so.2
#1  0x00007ffff752befd in luaL_loadfilex () from /lib64/libluajit-5.1.so.2
#2  0x00000000004de04d in ngx_http_lua_init_by_file (log=0x79cd98, lmcf=<optimized out>, L=0x0)
    at modules/ngx_http_lua_module/src/ngx_http_lua_initby.c:36
#3  0x00000000004db44f in ngx_http_lua_shared_memory_init (shm_zone=<optimized out>, data=<optimized out>)
    at modules/ngx_http_lua_module/src/ngx_http_lua_api.c:203
#4  0x000000000042d077 in ngx_init_cycle (old_cycle=old_cycle@entry=0x7fffffffe1e0) at src/core/ngx_cycle.c:533
#5  0x000000000041a0c6 in main (argc=<optimized out>, argv=<optimized out>) at src/core/nginx.c:320

```
This [commit](https://github.com/openresty/lua-nginx-module/commit/7c2b58ee7e66689ef176b251d43bfc84f7db26c6#diff-c91b2ec425e9be9d56fee2df662b67d2) made `ngx_http_lua_init ` run without `lmcf->lua = ngx_http_lua_init_vm(NULL, cf->cycle, cf->pool, lmcf, cf->log, NULL);` but the `lua_shared_dict ` will call `ngx_http_lua_init_by_file ` which it's argument `lua_State *L` is null.

**Comment by mrpre** [comment]
https://github.com/openresty/lua-nginx-module/issues/1462
