### ISSUE TITLE
 a coredound that may be triggered by lua coroutine

### ISSUE THREAD

**Issue by dupf0417** [openresty/lua-nginx-module#1518]
Hello，
I have a core problem that is suspected to be caused by the lua-nginx module.
* openresty-1.15.8.1rc1，Nginx and lua modules are official versions
* Can't reproduce, it will appear after long-running operation, and the recurrence time is unstable
*Although the stack file was corrupted and could not be parsed, we found the following stack log print in the system /var/log/messages, and the stack print is the same every time.

The reason for not being able to provide more references is that when trying to add a print recurring problem to find a problem, the problem is not present or the problem takes more time to appear. It will appear once in about three days now.
```
localhost systemd-coredump[30206]: Process 12408 (nginx) of user 1000 dumped core.#012#012Stack trace of thread 12408:#012#0  0x0000ffffae2a79e0 n/a (n/a)#012#1  0xfff9000000000003 n/a (n/a)#012#2  0x00000000004fd910 ngx_http_lua_run_thread (nginx)#012#3  0x0000000000507bdc ngx_http_lua_socket_handle_read_success (nginx)#012#4  0x0000000000507428 ngx_http_lua_socket_tcp_handler (nginx)#012#5  0x000000000044f2c8 ngx_epoll_process_events (nginx)#012#6  0x0000000000445dc4 ngx_process_events_and_timers (nginx)#012#7  0x000000000044d4b8 ngx_worker_process_cycle (nginx)#012#8  0x000000000044bd74 ngx_spawn_process (nginx)#012#9  0x000000000044d980 ngx_start_worker_processes (nginx)#012#10 0x000000000044e630 ngx_master_process_cycle (nginx)#012#11 0x0000000000425b1c main (nginx)#012#12 0x0000ffffac9e7ae0 __libc_start_main (libc.so.6)#012#13 0x0000000000426294 $x (nginx)#012#14 0x0000000000426294 $x (nginx)

```
* 
I also found this log print  like 
'G write guard:12: __newindex(): writing a global lua variable ('res') which may lead to race conditions between concurrent requests, so prefer the use of 'local' variables
Stack traceback:'
But I think the coredump should not be caused by this

**Comment by c1390528** [comment]
Hello, I have a similar problem. Is it solved?

`#0  ngx_http_lua_shdict_expire (n=2, n@entry=1, ctx=<optimized out>, ctx=<optimized out>) at ../ngx_lua-0.10.15/src/ngx_http_lua_shdict.c:282
#1  0x000000000056c750 in ngx_http_lua_ffi_shdict_get (zone=0x3874cf38, key=0x69852c008438 "node", key_len=4, value_type=0x69852c0023d0, str_value_buf=0x69852c046e48, str_value_len=0x69852c052d08, num_value=0x69852bfcee10, 
    user_flags=0xfff9000000000000, get_stale=0, is_stale=0x69852c002430, err=0x69852bff4328) at ../ngx_lua-0.10.15/src/ngx_http_lua_shdict.c:2526
#2  0x0000ffff93ad0334 in lj_vm_ffi_call () from /opt/huawei/openresty/luajit/lib/libluajit-5.1.so.2
#3  0x000069852c002430 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)`
