### ISSUE TITLE
nginx-1.19.3 t/020-subrequest.t avoid request smuggling 2/4 (POST capture + smuggle in body) failed

### ISSUE THREAD

**Issue by zhuizhuhaomeng** [openresty/lua-nginx-module#1808]
The out is below. 
We can see that  P is lost in `method: OST, uri: /foo` 

``` shell
[lijunlong@centos7-cube ~]$ curl http://127.0.0.1:1984/t
req bytes: 205
HTTP/1.1 200 OK
Server: nginx
Content-Type: text/plain
Transfer-Encoding: chunked
Connection: keep-alive

18
method: POST, uri: /foo

0

HTTP/1.1 200 OK
Server: nginx
Content-Type: text/plain
Transfer-Encoding: chunked
Connection: keep-alive

17
method: OST, uri: /foo

0
```

**Comment by zhuizhuhaomeng** [comment]
Use strace with the following command `strace -o strace_ok.log -s 300 -e trace=recvfrom,sendto,readv,writev -p 22764`
We found that the P of the `POST` is sent with the previous HTTP request's \n.

``` text
recvfrom(9, "GE", 1024, 0, NULL, NULL)  = 2
recvfrom(9, "T ", 1022, 0, NULL, NULL)  = 2
recvfrom(9, "/c", 1020, 0, NULL, NULL)  = 2
recvfrom(9, "ap", 1018, 0, NULL, NULL)  = 2
recvfrom(9, "tu", 1016, 0, NULL, NULL)  = 2
recvfrom(9, "re", 1014, 0, NULL, NULL)  = 2
recvfrom(9, " H", 1012, 0, NULL, NULL)  = 2
recvfrom(9, "TT", 1010, 0, NULL, NULL)  = 2
recvfrom(9, "P/", 1008, 0, NULL, NULL)  = 2
recvfrom(9, "1.", 1006, 0, NULL, NULL)  = 2
recvfrom(9, "1\n", 1004, 0, NULL, NULL) = 2
recvfrom(9, "Ho", 1002, 0, NULL, NULL)  = 2
recvfrom(9, "st", 1000, 0, NULL, NULL)  = 2
recvfrom(9, ": ", 998, 0, NULL, NULL)   = 2
recvfrom(9, "te", 996, 0, NULL, NULL)   = 2
recvfrom(9, "st", 994, 0, NULL, NULL)   = 2
recvfrom(9, ".c", 992, 0, NULL, NULL)   = 2
recvfrom(9, "om", 990, 0, NULL, NULL)   = 2
recvfrom(9, "\nC", 988, 0, NULL, NULL)  = 2
recvfrom(9, "on", 986, 0, NULL, NULL)   = 2
recvfrom(9, "te", 984, 0, NULL, NULL)   = 2
recvfrom(9, "nt", 982, 0, NULL, NULL)   = 2
recvfrom(9, "-L", 980, 0, NULL, NULL)   = 2
recvfrom(9, "en", 978, 0, NULL, NULL)   = 2
recvfrom(9, "gt", 976, 0, NULL, NULL)   = 2
recvfrom(9, "h:", 974, 0, NULL, NULL)   = 2
recvfrom(9, " 5", 972, 0, NULL, NULL)   = 2
recvfrom(9, "7\n", 970, 0, NULL, NULL)  = 2
recvfrom(9, "Tr", 968, 0, NULL, NULL)   = 2
recvfrom(9, "an", 966, 0, NULL, NULL)   = 2
recvfrom(9, "sf", 964, 0, NULL, NULL)   = 2
recvfrom(9, "er", 962, 0, NULL, NULL)   = 2
recvfrom(9, "-E", 960, 0, NULL, NULL)   = 2
recvfrom(9, "nc", 958, 0, NULL, NULL)   = 2
recvfrom(9, "od", 956, 0, NULL, NULL)   = 2
recvfrom(9, "in", 954, 0, NULL, NULL)   = 2
recvfrom(9, "g:", 952, 0, NULL, NULL)   = 2
recvfrom(9, " c", 950, 0, NULL, NULL)   = 2
recvfrom(9, "hu", 948, 0, NULL, NULL)   = 2
recvfrom(9, "nk", 946, 0, NULL, NULL)   = 2
recvfrom(9, "ed", 944, 0, NULL, NULL)   = 2
recvfrom(9, "\n\n", 942, 0, NULL, NULL) = 2
recvfrom(9, 0x1576760, 8192, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
recvfrom(9, "0\n", 8192, 0, NULL, NULL) = 2
recvfrom(9, "\nP", 8190, 0, NULL, NULL) = 2
recvfrom(9, "OST /capture HTTP/1.1\nHost: test.com\nContent-Length: 60\n\nPOST /bar HTTP/1.1\nHost: test.com\nContent-Length: 5\n\nhello\n\n", 939, 0, NULL, NULL) = 117
```

**Comment by zhuizhuhaomeng** [comment]
when there are pipelined requests, nginx copy it to the r->header_in but didn't change the r->request_body->buf

``` shell
#0  ngx_http_copy_pipelined_header (r=r@entry=0x2422790, buf=0x24236d0) at src/http/ngx_http_request_body.c:407
#1  0x000000000046f79d in ngx_http_do_read_client_request_body (r=0x2422790) at src/http/ngx_http_request_body.c:388
#2  0x000000000046fba7 in ngx_http_read_client_request_body_handler (r=0x2422790) at src/http/ngx_http_request_body.c:257
#3  0x000000000046597e in ngx_http_request_handler (ev=0x23d5b60) at src/http/ngx_http_request.c:2375
#4  0x0000000000443626 in ngx_event_process_posted (cycle=cycle@entry=0x23ce2d0, posted=0x7effb0 <ngx_posted_events>)
    at src/event/ngx_event_posted.c:34
#5  0x0000000000443137 in ngx_process_events_and_timers (cycle=cycle@entry=0x23ce2d0) at src/event/ngx_event.c:264
#6  0x000000000044cad2 in ngx_single_process_cycle (cycle=cycle@entry=0x23ce2d0) at src/os/unix/ngx_process_cycle.c:300
#7  0x0000000000423b34 in main (argc=<optimized out>, argv=<optimized out>) at src/core/nginx.c:379
```

In the funciton ngx_http_lua_subrequest  in  lua_nginx_module, there are:
sr->request_body = r->request_body;

``` shell
(gdb) bt
#0  ngx_http_lua_subrequest (flags=0, ps=0x16a9bb0, psr=<synthetic pointer>, args=0x7ffd0a2e0930, uri=0x7ffd0a2e0940, 
    r=<optimized out>) at /home/jiahao/work/org/lua-nginx-module/src/ngx_http_lua_subrequest.c:1417
#1  ngx_http_lua_ngx_location_capture_multi (L=L@entry=0x7f01bab3e848)
    at /home/jiahao/work/org/lua-nginx-module/src/ngx_http_lua_subrequest.c:580
#2  0x00000000004ec82f in ngx_http_lua_ngx_location_capture (L=0x7f01bab3e848)
    at /home/jiahao/work/org/lua-nginx-module/src/ngx_http_lua_subrequest.c:115
#3  0x00007f01ba07d1ed in lj_BC_FUNCC () from /opt/luajit21/lib/libluajit-5.1.so.2
#4  0x00000000004fc410 in ngx_http_lua_run_thread (L=L@entry=0x7f01bab28380, r=r@entry=0x16a8780, ctx=ctx@entry=0x16a94b8, 
    nrets=nrets@entry=0) at /home/jiahao/work/org/lua-nginx-module/src/ngx_http_lua_util.c:1129
#5  0x00000000004f312f in ngx_http_lua_read_body_resume (r=r@entry=0x16a8780)
    at /home/jiahao/work/org/lua-nginx-module/src/ngx_http_lua_req_body.c:1135
#6  0x00000000004f3277 in ngx_http_lua_req_body_post_read (r=0x16a8780)
    at /home/jiahao/work/org/lua-nginx-module/src/ngx_http_lua_req_body.c:186
#7  0x000000000046f7a6 in ngx_http_do_read_client_request_body (r=0x16a8780) at src/http/ngx_http_request_body.c:395
#8  0x000000000046fb29 in ngx_http_read_client_request_body_handler (r=0x16a8780) at src/http/ngx_http_request_body.c:257
#9  0x000000000046592e in ngx_http_request_handler (ev=0x165bc80) at src/http/ngx_http_request.c:2375
#10 0x00000000004435d6 in ngx_event_process_posted (cycle=cycle@entry=0x16542d0, posted=0x7edfb0 <ngx_posted_events>)
    at src/event/ngx_event_posted.c:34
#11 0x00000000004430e7 in ngx_process_events_and_timers (cycle=cycle@entry=0x16542d0) at src/event/ngx_event.c:264
#12 0x000000000044ca82 in ngx_single_process_cycle (cycle=cycle@entry=0x16542d0) at src/os/unix/ngx_process_cycle.c:300
#13 0x0000000000423ae4 in main (argc=<optimized out>, argv=<optimized out>) at src/core/nginx.c:379
(gdb) quit
```

**Comment by zhuizhuhaomeng** [comment]
I think this is a bug of nginx, the patch is here!
```
diff --git a/src/http/ngx_http_request_body.c b/src/http/ngx_http_request_body.c
index 71d7e9ab..fe075a87 100644
--- a/src/http/ngx_http_request_body.c
+++ b/src/http/ngx_http_request_body.c
@@ -472,6 +472,7 @@ ngx_http_copy_pipelined_header(ngx_http_request_t *r, ngx_buf_t *buf)
     }
 
     ngx_memcpy(b->last, buf->pos, n);
+    buf->last -= n;
 
     b->last += n;
     r->request_length -= n;
```

**Comment by spacewander** [comment]
I agree that it is bug of Nginx, but the fix looks strange to me. Maybe you can submit it to the nginx-devel mail list?
