### ISSUE TITLE
../modules/lua-nginx-module-0.9.15/src/ngx_http_lua_headers.c:405  coredump～ thanks！

### ISSUE THREAD

**Issue by yiliaofan** [openresty/lua-nginx-module#518]
use nginx 1.9.0
<pre>
(gdb) bt
#0  0x00007f7ea1ac78f7 in ?? () from /usr/local/lib/libluajit-5.1.so.2
#1  0x00007f7ea1acf3fb in lua_pushlstring () from /usr/local/lib/libluajit-5.1.so.2
#2  0x00000000004a4b42 in ngx_http_lua_ngx_req_get_headers (L=0x410b8510) at ../modules/lua-nginx-module-0.9.15/src/ngx_http_lua_headers.c:405
#3  0x00007f7ea1ac2e06 in ?? () from /usr/local/lib/libluajit-5.1.so.2
#4  0x00000000004b17ed in ngx_http_lua_run_thread (L=0x410a9378, r=0x15e06a0, ctx=0x165d1b0, nrets=0)
    at ../modules/lua-nginx-module-0.9.15/src/ngx_http_lua_util.c:1000
#5  0x00000000004b4242 in ngx_http_lua_content_by_chunk (L=0x410a9378, r=0x15e06a0)
    at ../modules/lua-nginx-module-0.9.15/src/ngx_http_lua_contentby.c:103
#6  0x00000000004b43e2 in ngx_http_lua_content_handler_file (r=0x15e06a0)
    at ../modules/lua-nginx-module-0.9.15/src/ngx_http_lua_contentby.c:267
#7  0x00000000004b4624 in ngx_http_lua_content_handler (r=0x15e06a0) at ../modules/lua-nginx-module-0.9.15/src/ngx_http_lua_contentby.c:205
#8  0x0000000000448c25 in ngx_http_core_content_phase (r=0x15e06a0, ph=0x1674200) at src/http/ngx_http_core_module.c:1392
#9  0x00000000004432f3 in ngx_http_core_run_phases (r=0x15e06a0) at src/http/ngx_http_core_module.c:873
#10 0x0000000000443410 in ngx_http_handler (r=<value optimized out>) at src/http/ngx_http_core_module.c:856
#11 0x000000000044e901 in ngx_http_process_request (r=0x15e06a0) at src/http/ngx_http_request.c:1902
#12 0x000000000044ef3c in ngx_http_process_request_headers (rev=<value optimized out>) at src/http/ngx_http_request.c:1333
#13 0x000000000044f4c0 in ngx_http_process_request_line (rev=0x7f7e9e2ca488) at src/http/ngx_http_request.c:1013
#14 0x000000000044fabf in ngx_http_wait_request_handler (rev=0x7f7e9e2ca488) at src/http/ngx_http_request.c:499
#15 0x0000000000430a9b in ngx_event_process_posted (cycle=0x15d4790, posted=0x7142f0) at src/event/ngx_event_posted.c:33
#16 0x000000000043081a in ngx_process_events_and_timers (cycle=0x15d4790) at src/event/ngx_event.c:266
#17 0x00000000004373b4 in ngx_worker_process_cycle (cycle=0x15d4790, data=<value optimized out>) at src/os/unix/ngx_process_cycle.c:767
#18 0x0000000000435ab1 in ngx_spawn_process (cycle=0x15d4790, proc=0x4372b9 <ngx_worker_process_cycle>, data=0x0, 
    name=0x4cf7d3 "worker process", respawn=-3) at src/os/unix/ngx_process.c:198
#19 0x00000000004367d6 in ngx_start_worker_processes (cycle=0x15d4790, n=8, type=-3) at src/os/unix/ngx_process_cycle.c:357
#20 0x0000000000437a45 in ngx_master_process_cycle (cycle=0x15d4790) at src/os/unix/ngx_process_cycle.c:129
#21 0x0000000000417a54 in main (argc=<value optimized out>, argv=<value optimized out>) at src/core/nginx.c:394
(gdb) bt full
#0  0x00007f7ea1ac78f7 in ?? () from /usr/local/lib/libluajit-5.1.so.2
No symbol table info available.
#1  0x00007f7ea1acf3fb in lua_pushlstring () from /usr/local/lib/libluajit-5.1.so.2
No symbol table info available.
#2  0x00000000004a4b42 in ngx_http_lua_ngx_req_get_headers (L=0x410b8510) at ../modules/lua-nginx-module-0.9.15/src/ngx_http_lua_headers.c:405
        part = 0x15e0710
        header = 0x165cdf0
        r = 0x15e06a0
        i = 5
        n = <value optimized out>
        max = <value optimized out>
        raw = 0
        count = 3
#3  0x00007f7ea1ac2e06 in ?? () from /usr/local/lib/libluajit-5.1.so.2
No symbol table info available.
#4  0x00000000004b17ed in ngx_http_lua_run_thread (L=0x410a9378, r=0x15e06a0, ctx=0x165d1b0, nrets=0)
    at ../modules/lua-nginx-module-0.9.15/src/ngx_http_lua_util.c:1000
        next_coctx = <value optimized out>
        parent_coctx = <value optimized out>
        orig_coctx = 0x165d1d8
        rv = <value optimized out>
        success = <value optimized out>
        next_co = <value optimized out>
        old_co = <value optimized out>
        err = <value optimized out>
        msg = <value optimized out>
        trace = <value optimized out>
        rc = <value optimized out>
        old_pool = 0x0
#5  0x00000000004b4242 in ngx_http_lua_content_by_chunk (L=0x410a9378, r=0x15e06a0)
    at ../modules/lua-nginx-module-0.9.15/src/ngx_http_lua_contentby.c:103
        co_ref = 1
        rc = <value optimized out>
        co = 0x410b8510
        ctx = 0x165d1b0
        cln = <value optimized out>
#6  0x00000000004b43e2 in ngx_http_lua_content_handler_file (r=0x15e06a0)
    at ../modules/lua-nginx-module-0.9.15/src/ngx_http_lua_contentby.c:267
---Type <return> to continue, or q <return> to quit---
        L = 0x410a9378
        rc = <value optimized out>
        script_path = <value optimized out>
        llcf = 0x161d670
        eval_src = {len = 51, data = 0x161d955 "/home/chenpeng/message/branches/luaDb/src/index.lua"}
#7  0x00000000004b4624 in ngx_http_lua_content_handler (r=0x15e06a0) at ../modules/lua-nginx-module-0.9.15/src/ngx_http_lua_contentby.c:205
        llcf = 0x161d670
        ctx = 0x165d1b0
        rc = <value optimized out>
#8  0x0000000000448c25 in ngx_http_core_content_phase (r=0x15e06a0, ph=0x1674200) at src/http/ngx_http_core_module.c:1392
        root = 140181796332680
        rc = <value optimized out>
        path = {len = 140181801662808, data = 0x15e06a0 "HTTP"}
#9  0x00000000004432f3 in ngx_http_core_run_phases (r=0x15e06a0) at src/http/ngx_http_core_module.c:873
        rc = <value optimized out>
        ph = 0x1674080
        cmcf = <value optimized out>
#10 0x0000000000443410 in ngx_http_handler (r=<value optimized out>) at src/http/ngx_http_core_module.c:856
        cmcf = <value optimized out>
#11 0x000000000044e901 in ngx_http_process_request (r=0x15e06a0) at src/http/ngx_http_request.c:1902
        c = 0x7f7e9e7df958
#12 0x000000000044ef3c in ngx_http_process_request_headers (rev=<value optimized out>) at src/http/ngx_http_request.c:1333
        p = <value optimized out>
        n = <value optimized out>
        rc = <value optimized out>
        rv = <value optimized out>
        h = <value optimized out>
        c = 0x7f7e9e7df958
        hh = <value optimized out>
        r = 0x15e06a0
        cscf = 0x16135d8
#13 0x000000000044f4c0 in ngx_http_process_request_line (rev=0x7f7e9e2ca488) at src/http/ngx_http_request.c:1013
        n = <value optimized out>
        rc = <value optimized out>
        rv = <value optimized out>
        host = {len = 140181801662808, data = 0x44c1f4 "H\211\203\360\003"}
        c = 0x7f7e9e7df958
        r = 0x15e06a0
---Type <return> to continue, or q <return> to quit---
#14 0x000000000044fabf in ngx_http_wait_request_handler (rev=0x7f7e9e2ca488) at src/http/ngx_http_request.c:499
        p = <value optimized out>
        size = 32768
        n = <value optimized out>
        b = 0x15d3bc8
        c = 0x7f7e9e7df958
        hc = 0x15d3b80
        cscf = <value optimized out>
#15 0x0000000000430a9b in ngx_event_process_posted (cycle=0x15d4790, posted=0x7142f0) at src/event/ngx_event_posted.c:33
        q = 0x7f7e9e2ca4d8
        ev = 0x7f7e9e2ca488
#16 0x000000000043081a in ngx_process_events_and_timers (cycle=0x15d4790) at src/event/ngx_event.c:266
        flags = 3
        timer = <value optimized out>
        delta = 0
#17 0x00000000004373b4 in ngx_worker_process_cycle (cycle=0x15d4790, data=<value optimized out>) at src/os/unix/ngx_process_cycle.c:767
        worker = <value optimized out>
        i = <value optimized out>
        c = <value optimized out>
#18 0x0000000000435ab1 in ngx_spawn_process (cycle=0x15d4790, proc=0x4372b9 <ngx_worker_process_cycle>, data=0x0, 
    name=0x4cf7d3 "worker process", respawn=-3) at src/os/unix/ngx_process.c:198
        on = 1
        pid = 0
        s = 0
#19 0x00000000004367d6 in ngx_start_worker_processes (cycle=0x15d4790, n=8, type=-3) at src/os/unix/ngx_process_cycle.c:357
        i = <value optimized out>
        ch = {command = 1, pid = 0, slot = 0, fd = 0}
#20 0x0000000000437a45 in ngx_master_process_cycle (cycle=0x15d4790) at src/os/unix/ngx_process_cycle.c:129
        title = 0x16755cc "master process sbin/nginx -p . -c conf/nginx.conf"
        p = <value optimized out>
        size = 50
        i = 5
        n = <value optimized out>
        sigio = <value optimized out>
        set = {__val = {0 <repeats 16 times>}}
        itv = {it_interval = {tv_sec = 22895432, tv_usec = 0}, it_value = {tv_sec = 0, tv_usec = 0}}
        live = <value optimized out>
        delay = <value optimized out>
---Type <return> to continue, or q <return> to quit---
        ls = <value optimized out>
        ccf = 0x15d5878
#21 0x0000000000417a54 in main (argc=<value optimized out>, argv=<value optimized out>) at src/core/nginx.c:394
        i = <value optimized out>
        log = 0x70f0a0
        cycle = 0x15d4790
        init_cycle = {conf_ctx = 0x0, pool = 0x15d3a20, log = 0x70f0a0, new_log = {log_level = 0, file = 0x0, connection = 0, 
            disk_full_time = 0, handler = 0, data = 0x0, writer = 0, wdata = 0x0, action = 0x0, next = 0x0}, log_use_stderr = 0, files = 0x0, 
          free_connections = 0x0, free_connection_n = 0, reusable_connections_queue = {prev = 0x0, next = 0x0}, listening = {elts = 0x0, 
            nelts = 0, size = 0, nalloc = 0, pool = 0x0}, paths = {elts = 0x0, nelts = 0, size = 0, nalloc = 0, pool = 0x0}, open_files = {
            last = 0x0, part = {elts = 0x0, nelts = 0, next = 0x0}, size = 0, nalloc = 0, pool = 0x0}, shared_memory = {last = 0x0, part = {
              elts = 0x0, nelts = 0, next = 0x0}, size = 0, nalloc = 0, pool = 0x0}, connection_n = 0, files_n = 0, connections = 0x0, 
          read_events = 0x0, write_events = 0x0, old_cycle = 0x0, conf_file = {len = 17, data = 0x15d3a72 "\300G\177"}, conf_param = {
            len = 0, data = 0x0}, conf_prefix = {len = 7, data = 0x15d3a72 "\300G\177"}, prefix = {len = 2, data = 0x15d3a70 "\002"}, 
          lock_file = {len = 0, data = 0x0}, hostname = {len = 0, data = 0x0}}
        ccf = <value optimized out>

</pre>

**Comment by yiliaofan** [comment]
solved

because my xlog nginx module caused

thank you
