### ISSUE TITLE
ngx.socket.connect got "bad request"

### ISSUE THREAD

**Issue by RustJason** [openresty/lua-nginx-module#706]
Hello, guys, I was using this fantastic repo recently and had written a small project using LUA. at the very beginning, everything was fine. But if I leave my page opened for a while and refresh it after serval minutes, I got a "Bad Request" error.
I am using resty's ]HTTP library](https://github.com/pintsized/lua-resty-http). and I am pretty sure this error was coming from [here](https://github.com/openresty/lua-nginx-module/blob/v0.10.0/src/ngx_http_lua_socket_tcp.c#L522):

```
522	            return luaL_error(L, "bad request");
(gdb) bt
#0  ngx_http_lua_socket_tcp_connect (L=0x7fb4c1a4ae40) at /tmp/lua-nginx-module-0.10.0//src/ngx_http_lua_socket_tcp.c:522
#1  0x00007fb4c5f19328 in luaD_precall () from /lib64/liblua-5.1.so
#2  0x00007fb4c5f23dd9 in luaV_execute () from /lib64/liblua-5.1.so
#3  0x00007fb4c5f18a6e in luaD_rawrunprotected () from /lib64/liblua-5.1.so
#4  0x00007fb4c5f197da in lua_resume () from /lib64/liblua-5.1.so
#5  0x00000000005173cc in ngx_http_lua_run_thread (L=0x7fb4c2c0ef80, r=0x7fb4c2ff2050, ctx=0x7fb4c2ff2e58, nrets=0) at /tmp/lua-nginx-module-0.10.0//src/ngx_http_lua_util.c:1015
#6  0x000000000051ea01 in ngx_http_lua_access_by_chunk (L=0x7fb4c2c0ef80, r=0x7fb4c2ff2050) at /tmp/lua-nginx-module-0.10.0//src/ngx_http_lua_accessby.c:315
#7  0x000000000051e7e8 in ngx_http_lua_access_handler_file (r=0x7fb4c2ff2050) at /tmp/lua-nginx-module-0.10.0//src/ngx_http_lua_accessby.c:232
#8  0x000000000051e63f in ngx_http_lua_access_handler (r=0x7fb4c2ff2050) at /tmp/lua-nginx-module-0.10.0//src/ngx_http_lua_accessby.c:163
#9  0x000000000045efc2 in ngx_http_core_access_phase (r=0x7fb4c2ff2050, ph=0x7fb4c2d62848) at src/http/ngx_http_core_module.c:1232
#10 0x000000000045e693 in ngx_http_core_run_phases (r=0x7fb4c2ff2050) at src/http/ngx_http_core_module.c:948
#11 0x000000000045e601 in ngx_http_handler (r=0x7fb4c2ff2050) at src/http/ngx_http_core_module.c:931
#12 0x000000000046e9c8 in ngx_http_process_request (r=0x7fb4c2ff2050) at src/http/ngx_http_request.c:1900
#13 0x000000000046d6a0 in ngx_http_process_request_headers (rev=0x7fb4c1806270) at src/http/ngx_http_request.c:1384
#14 0x000000000046cb72 in ngx_http_process_request_line (rev=0x7fb4c1806270) at src/http/ngx_http_request.c:1055
#15 0x000000000046b96f in ngx_http_wait_request_handler (rev=0x7fb4c1806270) at src/http/ngx_http_request.c:506
#16 0x000000000044b98b in ngx_epoll_process_events (cycle=0x7fb4c2cb1050, timer=30000, flags=1) at src/event/modules/ngx_epoll_module.c:691
#17 0x000000000043cd77 in ngx_process_events_and_timers (cycle=0x7fb4c2cb1050) at src/event/ngx_event.c:264
#18 0x0000000000449af8 in ngx_worker_process_cycle (cycle=0x7fb4c2cb1050, data=0x0) at src/os/unix/ngx_process_cycle.c:910
#19 0x0000000000444f8b in ngx_spawn_process (cycle=0x7fb4c2cb1050, proc=0x449954 <ngx_worker_process_cycle>, data=0x0, name=0x5484e8 "worker process", respawn=-3) at src/os/unix/ngx_process.c:189
#20 0x0000000000448b5c in ngx_start_worker_processes (cycle=0x7fb4c2cb1050, n=1, type=-3) at src/os/unix/ngx_process_cycle.c:409
#21 0x0000000000448205 in ngx_master_process_cycle (cycle=0x7fb4c2cb1050) at src/os/unix/ngx_process_cycle.c:143
#22 0x000000000041696d in main (argc=1, argv=0x7ffd1d21a828) at src/core/nginx.c:426
```

Since I am not familiar with Lua's API and don't know how `lua_touserdata` works. So I pasted this out and wondering if you guys have any clue about this. Could this happen because of `cache` or something?

BTW, my code was something like:

```lua
--function.lua
local http  = require "resty.http"
local httpc = http.new()
local JSON  = require "JSON"

local _MF = {}

local function refresh_auth_info()
        local session = ngx.shared.session
        --Refresh auth infomation from gitlab
        if session:get("timeout") == nil then

                local res, err = httpc:request_uri("https://bulabulabula", {
                        ssl_verify = false,
                        method     = "GET",
                })
        end
end

_MF.refresh_auth_info = refresh_auth_info
return _MF

--auther.lua
local comm = require "auth.function"
local http  = require "resty.http"
local httpc = http.new()
local JSON  = require "JSON"

--some code are omitted here
--blow is the line 54 which cause the error;
comm.refresh_auth_info()

```

Here is the Nginx error.

```
2016/03/11 20:48:04 [error] 37#0: *154 lua entry thread aborted: runtime error: /usr/share/nginx/lib/resty/http.lua:127: bad request
stack traceback:
coroutine 0:
	[C]: in function 'connect'
	/usr/share/nginx/lib/resty/http.lua:127: in function 'connect'
	/usr/share/nginx/lib/resty/http.lua:704: in function 'request_uri'
	/usr/share/nginx/lib/auth/function.lua:12: in function 'refresh_auth_info'
	/usr/share/nginx/lib/auth/auther.lua:54: in function </usr/share/nginx/lib/auth/auther.lua:1>, client: 10.209.76.76, server: localhost, request: "GET /auth?action=appmode HTTP/1.1", host: "test.xxx.cn"
```

Many thanks!

**Comment by agentzh** [comment]
@RustJason To quote the official documentation regarding cosockets:

"If you try to share the thread or cosocket objects across the boundary of the creating request, then you will get the "no co ctx found" error (for threads) or "bad request" (for cosockets)."

You are creating a cosocket and then share it across all the subsequent requests served by the current nginx worker by putting it on the Lua module, which is wrong. You should allocate an individual cosocket for each concurrent request (well, you can use connection pools though) to avoid conflicts. See

https://github.com/openresty/lua-nginx-module#data-sharing-within-an-nginx-worker

Never share a cosocket or light thread or a coroutine on the nginx worker level. You should only share normal Lua values, resty.lrucache objects, ngx.semaphore objects, lua shared dict objects, and etc.

**Comment by RustJason** [comment]
春哥威武！
