### ISSUE TITLE
Nginx - Worker Process Crash (Lua Parser)

### ISSUE THREAD

**Issue by Fr3DBr** [openresty/lua-nginx-module#939]
Hi, guys.

I'm trying to understand why the worker processes are crashing:

```
2016/12/23 20:03:24 [notice] 17865#0: signal 17 (SIGCHLD) received
2016/12/23 20:03:24 [alert] 17865#0: worker process 17870 exited on signal 6 (core dumped)
2016/12/23 20:03:24 [notice] 17865#0: start worker process 20965
2016/12/23 20:03:24 [notice] 17865#0: signal 29 (SIGIO) received
```

The crash core/dump in gdb looks like this:

```
#0  0x00006c44a743b5e5 in raise () from /lib64/libc.so.6
#1  0x00006c44a743cdc5 in abort () from /lib64/libc.so.6
#2  0x00000000004cc689 in ngx_http_lua_atpanic (L=0x45ce) at ../ngx_lua-0.10.5/src/ngx_http_lua_exception.c:34
#3  0x00006c44a82ba821 in mcode_protect (J=0x403ee558, prot=5) at lj_mcode.c:198
#4  0x00006c44a82dbffa in trace_stop (L=<value optimized out>, dummy=<value optimized out>, ud=0x1e1) at lj_trace.c:485
#5  trace_state (L=<value optimized out>, dummy=<value optimized out>, ud=0x1e1) at lj_trace.c:653
#6  0x00006c44a8291d4a in lj_vm_cpcall () from /usr/local/luajit/lib/libluajit-5.1.so.2
#7  0x00006c44a82dadef in lj_trace_ins (J=0x403ee558, pc=<value optimized out>) at lj_trace.c:684
#8  0x00006c44a829d875 in lj_dispatch_ins (L=0x40d3eff0, pc=0x40400be8) at lj_dispatch.c:424
#9  0x00006c44a8293345 in lj_vm_inshook () from /usr/local/luajit/lib/libluajit-5.1.so.2
#10 0x00000000004cfbf9 in ngx_http_lua_run_thread (L=0x403ee378, r=0x6c44a5740d80, ctx=0x6c44a5742040, nrets=0) at ../ngx_lua-0.10.5/src/ngx_http_lua_util.c:1015
#11 0x00000000004d36f4 in ngx_http_lua_access_by_chunk (L=0x403ee378, r=0x6c44a5740d80) at ../ngx_lua-0.10.5/src/ngx_http_lua_accessby.c:324
#12 0x00000000004d3c3b in ngx_http_lua_access_handler (r=0x6c44a5740d80) at ../ngx_lua-0.10.5/src/ngx_http_lua_accessby.c:163
#13 0x0000000000450a45 in ngx_http_core_access_phase (r=0x6c44a5740d80, ph=0x6c44a5715998) at src/http/ngx_http_core_module.c:1084
#14 0x000000000044ba9d in ngx_http_core_run_phases (r=0x6c44a5740d80) at src/http/ngx_http_core_module.c:858
#15 0x0000000000457a91 in ngx_http_process_request (r=0x6c44a5740d80) at src/http/ngx_http_request.c:1912
#16 0x000000000045892c in ngx_http_process_request_line (rev=0x6c4487e4b4f0) at src/http/ngx_http_request.c:1023
#17 0x0000000000441581 in ngx_epoll_process_events (cycle=0x6c44a8c7f870, timer=<value optimized out>, flags=<value optimized out>)
    at src/event/modules/ngx_epoll_module.c:822
#18 0x0000000000437aa5 in ngx_process_events_and_timers (cycle=0x6c44a8c7f870) at src/event/ngx_event.c:242
#19 0x000000000043f495 in ngx_worker_process_cycle (cycle=0x6c44a8c7f870, data=<value optimized out>) at src/os/unix/ngx_process_cycle.c:753
#20 0x000000000043d8d4 in ngx_spawn_process (cycle=0x6c44a8c7f870, proc=0x43f450 <ngx_worker_process_cycle>, data=0x4, name=0x5214e2 "worker process", respawn=-3)
    at src/os/unix/ngx_process.c:198
#21 0x000000000043e87c in ngx_start_worker_processes (cycle=0x6c44a8c7f870, n=8, type=-3) at src/os/unix/ngx_process_cycle.c:358
#22 0x000000000043fca3 in ngx_master_process_cycle (cycle=0x6c44a8c7f870) at src/os/unix/ngx_process_cycle.c:130
#23 0x000000000041c0bf in main (argc=<value optimized out>, argv=<value optimized out>) at src/core/nginx.c:367
```

The openresty version is: 1.9.15.1

There's no clear error in error_log, basically only the message saying the worker process stopped working and restarted.

*** I've tried migrating to: openresty-1.11.2.2 but the issue persists.

Forget it, this was caused by my custom kernel w/ grsecurity implemented, I had to allow nginx process to work in this environment. 👍

**Comment by Fr3DBr** [comment]
I've tried migrating to: openresty-1.11.2.2 but the issue persists.

**Comment by Fr3DBr** [comment]
This is a code which is crashing lua handler:

```
set_by_lua $addr '
        local tcs = ngx.var.remote_addr or ""
        local tce = ""
        local j = 0
        for i in string.gmatch(tcs, "%d+") do
                if j > 2 then
                        break
                end
                if j < 2 then
                        tce = tce .. i .. "."
                else
                        tce = tce .. i
                end
                j = j + 1
        end
        return tce
';
```

The code works, but for some reason, it causes the issue I've told you. Not sure why. :(
